apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
  labels:
    app: spring-api
spec:
  selector:
    matchLabels:
      app: spring-api-container
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-api-container
    spec:
      containers:
        - name: spring-api-container
          image: "gianmilani/jenkinstest:latest"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 256m
              memory: 100Mi